# Generated by Django 2.1.5 on 2019-01-21 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarifi', '0002_auto_20170910_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifiactivityslot',
            name='attender',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slots', to=settings.AUTH_USER_MODEL, verbose_name='Attender'),
        ),
        migrations.AlterField(
            model_name='tarifiuser',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Reception Date'),
        ),
        migrations.AlterField(
            model_name='tarifiuser',
            name='english_placement_test_slot',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'ENGLISH_PLACEMENT_TEST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_placement_slot', to='tarifi.TarifiActivitySlot', verbose_name='English Placement Test Slot'),
        ),
        migrations.AlterField(
            model_name='tarifiuser',
            name='english_speaking_test_slot',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'ENGLISH_SPEAKING_TEST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_speaking_slot', to='tarifi.TarifiActivitySlot', verbose_name='English Speaking Test Slot'),
        ),
        migrations.AlterField(
            model_name='tarifiuser',
            name='preparation_course_attended_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_students', to=settings.AUTH_USER_MODEL, verbose_name='Preparation Course Attended By'),
        ),
        migrations.AlterField(
            model_name='tarifiuser',
            name='preparation_course_slot',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'PREPARATION_COURSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_course_slot', to='tarifi.TarifiActivitySlot', verbose_name='Preparation Course Slot'),
        ),
        migrations.AlterField(
            model_name='tarifiuser',
            name='received_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_received', to=settings.AUTH_USER_MODEL, verbose_name='Received By'),
        ),
    ]
