# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type', models.CharField(max_length=20, null=True)),
                ('lookup_value_ar', models.CharField(max_length=100, null=True)),
                ('lookup_value_en', models.CharField(max_length=100, null=True)),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('display_order', models.PositiveSmallIntegerField(null=True, verbose_name='Display Order')),
            ],
            options={
                'ordering': ['-display_order'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='chronic_diseases',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chronic Diseases'),
        ),
    ]
