# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementitem',
            options={'ordering': ['agreement', '-display_order']},
        ),
        migrations.RemoveField(
            model_name='agreementitem',
            name='semester',
        ),
        migrations.AddField(
            model_name='agreementitem',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='undergraduate_admission.Agreement'),
        ),
    ]
