# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-10 08:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_committee_member',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Assigned Committee Member'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_picture_acceptable',
            field=models.NullBooleanField(verbose_name='Uploaded picture is acceptable?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=128, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_gpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='High School GPA (Ministry)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qudrat_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Qudrat Score (Qiyas)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahsili_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Tahsili Score (Qiyas)'),
        ),
    ]
