# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deniedstudent',
            name='last_trial_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deniedstudent',
            name='trials_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
