# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 11:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0002_auto_20160514_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationstatus',
            name='status_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Family Name (English)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_mobile',
            field=models.CharField(blank=True, help_text='Guardian mobile should be different than own mobile', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^966\\d{9}$', message='You have entered an invalid mobile number')], verbose_name='Guardian Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(help_text='Mobile number should be of this format "966xxxxxxxxx" ', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^966\\d{9}$', message='You have entered an invalid mobile number')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Name (English)'),
        ),
    ]
