# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-13 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0002_auto_20170710_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='high_school_major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Major'),
        ),
    ]
