# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0002_auto_20160503_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hs_full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='highschool_full_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deniedstudent',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denied_students', to='undergraduate_admission.AdmissionSemester'),
        ),
    ]
