# Generated by Django 2.1.5 on 2019-04-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0002_auto_20190415_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationstatus',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description for admin only', max_length=1500, null=True, verbose_name='Short Description'),
        ),
    ]
