# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0002_auto_20160508_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['display_order', 'nationality_en'], 'verbose_name_plural': 'nationalities'},
        ),
        migrations.AlterField(
            model_name='agreementitem',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
