# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 12:06
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0003_auto_20160515_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHelpDisk',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('undergraduate_admission.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='agreementitem',
            name='agreement_text_ar',
            field=models.TextField(max_length=2000, verbose_name='Agreement Text (Arabic)'),
        ),
        migrations.AlterField(
            model_name='agreementitem',
            name='agreement_text_en',
            field=models.TextField(max_length=2000, verbose_name='Agreement Text (English)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_mobile',
            field=models.CharField(blank=True, help_text='Guardian mobile should be different than own mobile', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^9665\\d{8}$', message='You have entered an invalid mobile number')], verbose_name='Guardian Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(help_text='Mobile number should be of this format "9665xxxxxxxx" ', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^9665\\d{8}$', message='You have entered an invalid mobile number')], verbose_name='Mobile'),
        ),
    ]
