# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0003_auto_20160508_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistinguishedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_id', models.CharField(max_length=12)),
                ('student_name', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('attended', models.NullBooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='agreement',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement', to='undergraduate_admission.AdmissionSemester'),
        ),
    ]
