# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0003_auto_20160504_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hs_graduation_year',
        ),
        migrations.AddField(
            model_name='user',
            name='highschhol_graduation_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='undergraduate_admission.GraduationYear'),
        ),
    ]
