# Generated by Django 2.1.5 on 2019-04-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0003_registrationstatus_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationstatus',
            name='status_message_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registrationstatus',
            unique_together={('general_status', 'status_message_code')},
        ),
    ]
