# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0003_user_high_school_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifiActivitySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start_date', models.DateTimeField(null=True, verbose_name='Start Date')),
                ('slot_end_date', models.DateTimeField(null=True, verbose_name='End Date')),
                ('location_ar', models.CharField(max_length=600, null=True, verbose_name='Location (Arabic)')),
                ('location_en', models.CharField(max_length=600, null=True, verbose_name='Location (English)')),
                ('slots', models.PositiveSmallIntegerField(default=300, null=True, verbose_name='Slots')),
                ('type', models.CharField(choices=[('PREPARATION_COURSE', 'Preparation Course Attendance Date'), ('ENGLISH_PLACEMENT_TEST', 'English Placement Test Date'), ('ENGLISH_SPEAKING_TEST', 'English Speaking Test Date')], max_length=30, null=True, verbose_name='Slot Type')),
                ('description', models.CharField(blank=True, max_length=600, null=True, verbose_name='Description')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('display_order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display Order')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifi_activities_dates', to='undergraduate_admission.AdmissionSemester', verbose_name='Semester')),
            ],
            options={
                'verbose_name_plural': 'Tarifi: Preparation Activity Slots',
            },
        ),
        migrations.AlterModelOptions(
            name='tarifireceptiondate',
            options={'verbose_name_plural': 'Tarifi: Tarifi Reception Dates'},
        ),
        migrations.AddField(
            model_name='tarifireceptiondate',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='tarifireceptiondate',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarifi_week_attendance_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='undergraduate_admission.TarifiReceptionDate', verbose_name='Tarifi Week Attendance Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_picture_acceptable',
            field=models.NullBooleanField(verbose_name='Uploaded picture is rejected?'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_placement_test_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_placement_slot', to='undergraduate_admission.TarifiActivitySlot', verbose_name='English Placement Test Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_speaking_test_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_speaking_slot', to='undergraduate_admission.TarifiActivitySlot', verbose_name='English Speaking Test Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='preparation_course_attendance_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_course_slot', to='undergraduate_admission.TarifiActivitySlot', verbose_name='Preparation Course Attendance Date'),
        ),
    ]
