# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0004_auto_20170718_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifiactivityslot',
            name='semester',
        ),
        migrations.AlterModelOptions(
            name='tarifireceptiondate',
            options={'ordering': ['slot_start_date'], 'verbose_name_plural': 'Tarifi: Tarifi Reception Dates'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_placement_test_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_placement_test_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_speaking_test_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='english_speaking_test_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preparation_course_attendance_date',
        ),
        migrations.AddField(
            model_name='user',
            name='admission_note2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Admission Note 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='admission_note3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Admission Note 3'),
        ),
        migrations.DeleteModel(
            name='TarifiActivitySlot',
        ),
    ]
