# Generated by Django 2.1.5 on 2019-04-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0004_auto_20190423_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequest',
            name='high_school_system',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('INTERNATIONAL', 'International')], max_length=100, null=True, verbose_name='High School System'),
        ),
    ]
