# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0004_auto_20160509_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementitem',
            name='show_flag',
        ),
        migrations.RemoveField(
            model_name='agreementitem',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='agreementitem',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='city',
            name='show_flag',
        ),
        migrations.RemoveField(
            model_name='graduationyear',
            name='show_flag',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='show_flag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='high_school_full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qiyas_first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qiyas_last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qiyas_second_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qiyas_third_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='agreementitem',
            name='show',
            field=models.NullBooleanField(verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='city',
            name='show',
            field=models.NullBooleanField(verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='graduationyear',
            name='show',
            field=models.NullBooleanField(verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='show',
            field=models.NullBooleanField(verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='user',
            name='admission_letter_note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Admission Letter Note'),
        ),
        migrations.AddField(
            model_name='user',
            name='admission_letter_print_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Admission Letter Print Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_certificate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birth Date Certificate'),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Blood Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='courses_certificate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Courses Certificate'),
        ),
        migrations.AddField(
            model_name='user',
            name='disability_needs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Disability Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='employer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employeer Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employeement'),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Family Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Family Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Government ID Expiry Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Government ID File'),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_issue',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Government ID Issue Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Place of Issue'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian City'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_employer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Employer'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_government_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Government ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Work'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_po_box',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian PO Box'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Postal Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Relation'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_certificate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Certificate'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School City'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Province'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School System'),
        ),
        migrations.AddField(
            model_name='user',
            name='kids_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of Kids'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_report_print_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Medical Report Print Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_gov_id_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mother Government ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='other_needs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other Disability'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Passport Expiry Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Upload Passport'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Password Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport Place of Issue '),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_picture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personal Picture'),
        ),
        migrations.AddField(
            model_name='user',
            name='phase2_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 2 End Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='phase2_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 2 Start Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='phase2_submit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 2 Submit Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative City'),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_employer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative Employer'),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative Work'),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative Mobile'),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_po_box',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative PO Box'),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_po_stal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative PO Box'),
        ),
        migrations.AddField(
            model_name='user',
            name='relative_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative Relation'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Social Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Student Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Student Notes'),
        ),
        migrations.AddField(
            model_name='user',
            name='third_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Verification Note'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Verification Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Withdrawal Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Withdrawal Reason'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_university',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Withdrew To University'),
        ),
        migrations.AlterField(
            model_name='admissionsemester',
            name='high_school_gpa_weight',
            field=models.FloatField(null=True, verbose_name='High School GPA Weight'),
        ),
        migrations.AlterField(
            model_name='admissionsemester',
            name='phase1_end_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 1 End Date'),
        ),
        migrations.AlterField(
            model_name='admissionsemester',
            name='phase1_start_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 1 Start Date'),
        ),
        migrations.AlterField(
            model_name='admissionsemester',
            name='phase2_end_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 2 End Date'),
        ),
        migrations.AlterField(
            model_name='admissionsemester',
            name='phase2_start_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 2 Start Date'),
        ),
        migrations.AlterField(
            model_name='admissionsemester',
            name='qudrat_score_weight',
            field=models.FloatField(null=True, verbose_name='Qudrat Score Weight'),
        ),
        migrations.AlterField(
            model_name='admissionsemester',
            name='semester_name',
            field=models.CharField(max_length=200, verbose_name='Semester Name'),
        ),
        migrations.AlterField(
            model_name='admissionsemester',
            name='tahsili_score_weight',
            field=models.FloatField(null=True, verbose_name='Tahsili Score Weight'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_footer_ar',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Agreement Footer (Arabic)'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_footer_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Agreement Footer (English)'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_header_ar',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Agreement Header (Arabic)'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_header_en',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Agreement Header (English)'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Agreement Type'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement', to='undergraduate_admission.AdmissionSemester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='agreementitem',
            name='agreement_text_ar',
            field=models.CharField(max_length=2000, verbose_name='Agreement Text (Arabic)'),
        ),
        migrations.AlterField(
            model_name='agreementitem',
            name='agreement_text_en',
            field=models.CharField(max_length=2000, verbose_name='Agreement Text (English)'),
        ),
        migrations.AlterField(
            model_name='agreementitem',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_ar',
            field=models.CharField(max_length=100, verbose_name='City Name Arabic'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=100, verbose_name='City Name English'),
        ),
        migrations.AlterField(
            model_name='city',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='deniedstudent',
            name='government_id',
            field=models.CharField(max_length=12, verbose_name='Government ID'),
        ),
        migrations.AlterField(
            model_name='deniedstudent',
            name='last_trial_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Trial Date'),
        ),
        migrations.AlterField(
            model_name='deniedstudent',
            name='message',
            field=models.CharField(max_length=400, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='deniedstudent',
            name='student_name',
            field=models.CharField(max_length=400, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='deniedstudent',
            name='trials_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Count Trial'),
        ),
        migrations.AlterField(
            model_name='deniedstudent',
            name='university_code',
            field=models.CharField(max_length=10, verbose_name='University Code'),
        ),
        migrations.AlterField(
            model_name='distinguishedstudent',
            name='attended',
            field=models.NullBooleanField(verbose_name='Attended'),
        ),
        migrations.AlterField(
            model_name='distinguishedstudent',
            name='city',
            field=models.CharField(max_length=400, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='distinguishedstudent',
            name='government_id',
            field=models.CharField(max_length=12, verbose_name='Government ID'),
        ),
        migrations.AlterField(
            model_name='distinguishedstudent',
            name='student_name',
            field=models.CharField(max_length=400, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='graduation_year_ar',
            field=models.CharField(max_length=50, verbose_name='Graduation Year (Arabic)'),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='graduation_year_en',
            field=models.CharField(max_length=50, verbose_name='Graduation Year (English)'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='display_order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='nationality_ar',
            field=models.CharField(max_length=50, verbose_name='Nationality (Arabic)'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='nationality_en',
            field=models.CharField(max_length=50, verbose_name='Nationality (English)'),
        ),
        migrations.AlterField(
            model_name='registrationstatus',
            name='status_ar',
            field=models.CharField(max_length=50, verbose_name='Status (Arabic)'),
        ),
        migrations.AlterField(
            model_name='registrationstatus',
            name='status_en',
            field=models.CharField(max_length=50, verbose_name='Status (English)'),
        ),
        migrations.AlterField(
            model_name='registrationstatusmessage',
            name='status_message_ar',
            field=models.CharField(max_length=500, verbose_name='Registration Status Message AR'),
        ),
        migrations.AlterField(
            model_name='registrationstatusmessage',
            name='status_message_en',
            field=models.CharField(max_length=500, verbose_name='Registration Status Message EN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='admission_note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Admission Note'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_ah',
            field=models.CharField(max_length=50, null=True, verbose_name='Birthday Hijri'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name (English)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Guardian Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_gpa',
            field=models.FloatField(blank=True, null=True, verbose_name='High School GPA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_graduation_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='undergraduate_admission.GraduationYear', verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kfupm_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='KFUPM ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='undergraduate_admission.Nationality', verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qudrat_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Qudrat Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saudi_mother',
            field=models.NullBooleanField(verbose_name='Saudi Mother'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Second Name (English)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='undergraduate_admission.AdmissionSemester', verbose_name='Admission Semester'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='undergraduate_admission.RegistrationStatusMessage', verbose_name='Message Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahsili_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Tahsili Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='third_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Name (Arabic)'),
        ),
    ]
