# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0004_auto_20160517_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_notes',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Student Notes'),
        ),
    ]
