# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0004_auto_20160504_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='highschhol_graduation_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='highschool_full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_full_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_graduation_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='undergraduate_admission.GraduationYear'),
        ),
    ]
