# Generated by Django 2.1.5 on 2019-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0005_auto_20190427_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationstatus',
            options={'ordering': ('short_description',), 'verbose_name_plural': 'Admission: Registration Status'},
        ),
        migrations.AddField(
            model_name='agreement',
            name='short_description',
            field=models.TextField(help_text='Short description for admin only', max_length=1500, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='registrationstatus',
            name='general_status',
            field=models.CharField(choices=[('1-APPLIED', 'Applied'), ('2-PARTIALLY-ADMITTED', 'Partially-Admitted'), ('3-ADMITTED', 'Admitted'), ('4-SUSPENDED', 'Suspended'), ('5-REJECTED', 'Rejected'), ('6-WITHDRAWN', 'Withdrawn')], max_length=200, null=True, verbose_name='General Status'),
        ),
        migrations.AlterField(
            model_name='registrationstatus',
            name='short_description',
            field=models.TextField(help_text='Short description for admin only', max_length=1500, null=True, verbose_name='Short Description'),
        ),
    ]
