# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0005_auto_20170727_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationstatusmessage',
            options={'ordering': ('status_message_code',), 'verbose_name_plural': 'Admission: Registration Status Messages'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='high_school_major',
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicator of the current active semester. This will be used in the admin-side and committee pages', verbose_name='Active Semester'),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Government ID Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_city_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='High School City Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_city_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School City (English)'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='High School ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_major_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='High School Major Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_major_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Major Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_major_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Major Name (English)'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Name (English)'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_province_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='High School Province Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_province_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Province (English)'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Owner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='government_id_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Government ID Issue Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School City (Arabic)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='High School Province (Arabic)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date'),
        ),
    ]
