# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 12:10
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0005_auto_20160519_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('undergraduate_admission.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
