# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 09:47
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0006_userauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHelpDisk',
        ),
        migrations.CreateModel(
            name='HelpDiskForStudent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('undergraduate_admission.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
