# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-15 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0006_auto_20180404_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifireceptiondate',
            options={'ordering': ['slot_start_date'], 'verbose_name_plural': 'Orientation Week: Schedule'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'Users: Change Password'},
        ),
    ]
