# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0007_auto_20160524_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuth',
        ),
    ]
