# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0007_auto_20180516_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account'),
        ),
    ]
