# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-23 11:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0008_auto_20180522_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Your International Bank Account Number (IBAN) for your own Saudi bank account. Your IBAN format should be SA followed by 22 digits.', max_length=50, null=True, validators=[django.core.validators.RegexValidator('^(SA)\\d{22}$', message='You have entered an invalid IBAN')], verbose_name='Your IBAN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
    ]
