# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0009_auto_20160526_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='lookup_type',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
