# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 11:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0010_auto_20160526_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, help_text='Mobile number should be of this format "9665xxxxxxxx". Use English numerals only.', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^9665\\d{8}$', message='You have entered an invalid mobile number')], verbose_name='Mobile'),
        ),
    ]
