# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0010_auto_20180610_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationyear',
            name='type',
            field=models.CharField(choices=[('CURRENT-YEAR', 'Current high school graduation year'), ('LAST-YEAR', 'Previous high school graduation year'), ('OLD-HS', 'Old High school graduation year')], default='OLD-HS', max_length=20, null=True, verbose_name='Type'),
        ),
    ]
