# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import undergraduate_admission.media_handlers
import undergraduate_admission.validators


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0013_auto_20160604_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_birth, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Birth Date Certificate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='government_id_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_govid, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Government ID File'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_certificate',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_certificate, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='High School Certificate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mother_gov_id_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_mother_govid, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Mother Government ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_passport, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Upload Passport'),
        ),
    ]
