# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import undergraduate_admission.media_handlers
import undergraduate_admission.validators


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0014_auto_20160605_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_picture',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_picture, validators=[undergraduate_admission.validators.validate_image_extension], verbose_name='Personal Picture'),
        ),
    ]
