# Generated by Django 2.1.5 on 2019-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0014_auto_20190126_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_field', models.CharField(choices=[('personal_picture', 'Personal Picture'), ('high_school_certificate', 'High School Certificate')], db_index=True, max_length=20, null=True, verbose_name='Related Field')),
                ('verification_issue_ar', models.CharField(max_length=100, null=True, verbose_name='Verification Issue (AR)')),
                ('verification_issue_en', models.CharField(max_length=100, null=True, verbose_name='Verification Issue (EN)')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('display_order', models.PositiveSmallIntegerField(null=True, verbose_name='Display Order')),
            ],
            options={
                'verbose_name_plural': 'Verification Issues',
                'ordering': ['related_field', '-display_order'],
            },
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='verification_issues',
            field=models.ManyToManyField(blank=True, related_name='student_issues', to='undergraduate_admission.VerificationIssues', verbose_name='Verification Issues'),
        ),
    ]
