# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0015_auto_20160605_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='government_id_expiry',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Government ID Expiry Date'),
        ),
    ]
