# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0016_auto_20160608_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employer_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employer Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='government_id_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Government ID Place of Issue'),
        ),
    ]
