# Generated by Django 2.1.5 on 2019-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0016_auto_20190127_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationissues',
            name='related_field',
            field=models.CharField(choices=[('personal_picture', 'Personal Picture'), ('high_school_certificate', 'High School Certificate')], db_index=True, max_length=50, null=True, verbose_name='Related Field'),
        ),
        migrations.AlterField(
            model_name='verificationissues',
            name='verification_issue_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Verification Issue (AR)'),
        ),
        migrations.AlterField(
            model_name='verificationissues',
            name='verification_issue_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Verification Issue (EN)'),
        ),
    ]
