# Generated by Django 2.1.5 on 2019-04-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0017_auto_20190127_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='status',
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='withdrawal_deadline',
            field=models.DateTimeField(null=True, verbose_name='Withdrawal Deadline'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='status_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='undergraduate_admission.RegistrationStatusMessage', verbose_name='Status Message'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='agreement_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Agreements'), ('CONFIRM', 'Confirmation Agreements'), ('STUDENT-AGREEMENT_1', 'Student ِAgreements 1'), ('STUDENT-AGREEMENT_2', 'Student Agreements 2'), ('STUDENT-AGREEMENT_3', 'Student Agreements 3'), ('STUDENT-AGREEMENT_4', 'Student Agreements 4'), ('HOUSING-AGREEMENT', 'Student Housing: Initial Agreements'), ('HOUSING-ROOMMATE-REQUEST-AGREEMENT', 'Student Housing: Request Agreements'), ('HOUSING-ROOMMATE-SEARCH-INSTRUCTIONS', 'Student Housing: Search Instructions'), ('HOUSING-ROOMMATE-REQUEST-INSTRUCTIONS', 'Student Housing: Request Instructions'), ('AWARENESS-WEEK-AGREEMENT', 'Awareness Week Agreements')], max_length=100, null=True, verbose_name='Agreement Type'),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='lookup_type',
            field=models.CharField(choices=[('BANK_NAMES', 'Bank Names'), ('BLOOD_TYPE', 'Blood Type'), ('CHRONIC_DISEASES', 'Chronic Diseases'), ('DISABILITY', 'Disability'), ('EMPLOYMENT_STATUS', 'Employment Status'), ('HIGH_SCHOOL_TYPE', 'High_school Type'), ('HOUSING_PREF_AC', 'Housing Preference AC'), ('HOUSING_PREF_LIGHT', 'Housing Preference Light'), ('HOUSING_PREF_SLEEPIN', 'Housing Preference Sleepin'), ('HOUSING_PREF_VISITS', 'Housing Preference Visits'), ('PERSON_RELATION', 'Person Relation'), ('SOCIAL_STATUS', 'Social Status'), ('UNIVERSITY', 'University'), ('VEHICLE_OWNER', 'Vehicle Owner')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='verificationissues',
            name='related_field',
            field=models.CharField(choices=[('personal_picture', 'Personal Picture'), ('high_school_certificate', 'High School Certificate'), ('mother_gov_id_file', 'Mother Government ID')], db_index=True, max_length=50, null=True, verbose_name='Related Field'),
        ),
    ]
