# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0017_auto_20160608_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chronic_diseases_notes',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Chronic Diseases Notes'),
        ),
    ]
