# Generated by Django 2.1.5 on 2019-04-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0018_auto_20190403_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationstatusmessage',
            name='status',
        ),
        migrations.AlterModelOptions(
            name='registrationstatus',
            options={'ordering': ('general_status', 'status_message_code'), 'verbose_name_plural': 'Admission: Registration Status'},
        ),
        migrations.RenameField(
            model_name='registrationstatus',
            old_name='status_code',
            new_name='status_message_code',
        ),
        migrations.RemoveField(
            model_name='registrationstatus',
            name='status_ar',
        ),
        migrations.RemoveField(
            model_name='registrationstatus',
            name='status_en',
        ),
        migrations.AddField(
            model_name='registrationstatus',
            name='general_status',
            field=models.CharField(choices=[('1-APPLIED', 'Phase 1: Applied'), ('2-PARTIALLY-ADMITTED', 'Phase 2: Partially-Admitted'), ('3-ADMITTED', 'Phase 3: Admitted'), ('4-SUSPENDED', 'Phase 3: Suspended'), ('5-REJECTED', 'Rejected'), ('6-WITHDRAWN', 'Withdrawn')], max_length=200, null=True, verbose_name='General Status'),
        ),
        migrations.AddField(
            model_name='registrationstatus',
            name='status_message_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='Registration Status Message AR'),
        ),
        migrations.AddField(
            model_name='registrationstatus',
            name='status_message_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Registration Status Message EN'),
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='status_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='undergraduate_admission.RegistrationStatus', verbose_name='Message Status'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='undergraduate_admission.RegistrationStatus', verbose_name='Status Message'),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='lookup_type',
            field=models.CharField(choices=[('BANK_NAMES', 'Bank Names'), ('BLOOD_TYPE', 'Blood Type'), ('CHRONIC_DISEASES', 'Chronic Diseases'), ('DISABILITY', 'Disability'), ('EMPLOYMENT_STATUS', 'Employment Status'), ('HIGH_SCHOOL_TYPE', 'High School Type'), ('HOUSING_PREF_AC', 'Housing Preference AC'), ('HOUSING_PREF_LIGHT', 'Housing Preference Light'), ('HOUSING_PREF_SLEEPIN', 'Housing Preference Sleepin'), ('HOUSING_PREF_VISITS', 'Housing Preference Visits'), ('PERSON_RELATION', 'Person Relation'), ('SOCIAL_STATUS', 'Social Status'), ('UNIVERSITY', 'University'), ('VEHICLE_OWNER', 'Vehicle Owner')], db_index=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='RegistrationStatusMessage',
        ),
    ]
