# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import undergraduate_admission.media_handlers
import undergraduate_admission.validators


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0018_user_chronic_diseases_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses_certificate',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_courses, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Courses Certificate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Guardian Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='other_needs',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Other Disability'),
        ),
        migrations.AlterField(
            model_name='user',
            name='relative_po_stal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relative Postal Code'),
        ),
    ]
