# Generated by Django 2.1.5 on 2019-04-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0019_auto_20190403_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationstatus',
            name='status_message_ar',
            field=models.TextField(max_length=1500, null=True, verbose_name='Registration Status Message AR'),
        ),
        migrations.AlterField(
            model_name='registrationstatus',
            name='status_message_en',
            field=models.TextField(max_length=1500, null=True, verbose_name='Registration Status Message EN'),
        ),
    ]
