# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0020_auto_20160609_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employment',
        ),
    ]
