# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0022_user_is_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_employed',
            field=models.BooleanField(default=False, help_text='It is required that applicant be unemployed to be full-time. In case you are currently employed, you need to bring clearance from your employer.', verbose_name='Are You Employed?'),
        ),
    ]
