# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0024_auto_20160612_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kfupm_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='KFUPM ID'),
        ),
    ]
