# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0026_auto_20160613_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationstatusmessage',
            name='status_message_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_ah',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birthday Hijri'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
