# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0027_auto_20160613_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Country and city. e.g. Saudi Arabia Jeddah', max_length=100, null=True, verbose_name='Birth Place'),
        ),
        migrations.AlterField(
            model_name='registrationstatus',
            name='status_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registrationstatusmessage',
            name='status_message_code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
