# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0028_auto_20160613_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='guardian_phone',
            field=models.CharField(blank=True, help_text='With country and area code. e.g. 966138602722', max_length=50, null=True, verbose_name='Guardian Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='With country and area code. e.g. 966138602722', max_length=50, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='relative_phone',
            field=models.CharField(blank=True, help_text='With country and area code. e.g. 966138602722', max_length=50, null=True, verbose_name='Relative Mobile'),
        ),
    ]
