# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 08:31
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0029_auto_20160615_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyStudent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('undergraduate_admission.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
