# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0031_user_verification_docs_incomplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_docs_incomplete',
            new_name='verification_documents_incomplete',
        ),
    ]
