# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-07 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0033_auto_20160620_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eligible_for_housing',
            field=models.NullBooleanField(verbose_name='Eligible For Housing'),
        ),
    ]
