# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-10 13:35
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import undergraduate_admission.media_handlers
import undergraduate_admission.validators


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0034_user_eligible_for_housing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDateSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Arabic Title')),
                ('title_en', models.CharField(max_length=200, verbose_name='English Title')),
                ('description_ar', models.CharField(max_length=300, null=True, verbose_name='Arabic Description')),
                ('description_en', models.CharField(max_length=300, null=True, verbose_name='English Description')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('display_order', models.PositiveSmallIntegerField(null=True, verbose_name='Display Order')),
            ],
            options={
                'verbose_name_plural': 'Admission: Important Date Sidebar',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='TarifiReceptionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_date', models.CharField(max_length=600, null=True, verbose_name='Reception Date')),
                ('slots', models.PositiveSmallIntegerField(default=300, null=True, verbose_name='Slots')),
                ('slot_start_date', models.DateTimeField(null=True, verbose_name='Start Date')),
                ('slot_end_date', models.DateTimeField(null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name_plural': 'Admission: Tarifi Reception Dates',
            },
        ),
        migrations.CreateModel(
            name='CutOff',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('undergraduate_admission.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='admissionsemester',
            options={'verbose_name': 'Admission Semester', 'verbose_name_plural': 'Admission: Admission Semesters'},
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name_plural': 'Admission and Student Affairs: Agreements'},
        ),
        migrations.AlterModelOptions(
            name='agreementitem',
            options={'ordering': ['agreement', '-display_order'], 'verbose_name_plural': 'Admission and Student Affairs: Agreement Items'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-display_order'], 'verbose_name_plural': 'Admission: Cities'},
        ),
        migrations.AlterModelOptions(
            name='deniedstudent',
            options={'verbose_name_plural': 'Admission: Denied Students'},
        ),
        migrations.AlterModelOptions(
            name='distinguishedstudent',
            options={'verbose_name_plural': 'Admission: Distinguished Students'},
        ),
        migrations.AlterModelOptions(
            name='graduationyear',
            options={'ordering': ['-display_order'], 'verbose_name_plural': 'Admission: Graduation Years'},
        ),
        migrations.AlterModelOptions(
            name='kfupmidspool',
            options={'verbose_name_plural': 'Registrar: KFUPM ID Pools'},
        ),
        migrations.AlterModelOptions(
            name='lookup',
            options={'ordering': ['lookup_type', '-display_order'], 'verbose_name_plural': 'Admission: Look ups'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['display_order', 'nationality_en'], 'verbose_name_plural': 'Admission: Nationalities'},
        ),
        migrations.AlterModelOptions(
            name='registrationstatus',
            options={'verbose_name_plural': 'Admission: Registration Status'},
        ),
        migrations.AlterModelOptions(
            name='registrationstatusmessage',
            options={'verbose_name_plural': 'Admission: Registration Status Messages'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='admission_letter_note',
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='phase3_end_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 3 End Date'),
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='phase3_start_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 3 Start Date'),
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='phase4_end_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 4 End Date'),
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='phase4_start_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 4 Start Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_driving_license, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Driving License File'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='English Level'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_placement_test_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='English Placement Test Score'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_speaking_test_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='English Speaking Test Score'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='have_a_vehicle',
            field=models.BooleanField(default=False, help_text='This will let us help you better to get you a permit to enter campus.', verbose_name='Do you have a vehicle you want to register?'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_gpa_yesser',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='High School GPA - Yesser'),
        ),
        migrations.AddField(
            model_name='user',
            name='qudrat_score_yesser',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Qudrat Score - Yesser'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_full_name_ar',
            field=models.CharField(blank=True, help_text='Your Arabic full name should be similar to Identification ID/Iqama.', max_length=400, null=True, verbose_name='Student Full Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_full_name_en',
            field=models.CharField(blank=True, help_text='Your English full name should be similar to Passport or high school certificate.', max_length=400, null=True, verbose_name='Student Full Name (English)'),
        ),
        migrations.AddField(
            model_name='user',
            name='tahsili_score_yesser',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Tahsili Score - Yesser'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_plate_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Plate No.'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_registration_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_vehicle_registration, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Vehicle Registration File'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_gpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='High School GPA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, help_text='Mobile number should be of this format "9665xxxxxxxx". Use English numerals only. Please make sure to activate promotional messages from your mobile provider.', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^(9665|٩٦٦٥)\\d{8}$', message='You have entered an invalid mobile number')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qudrat_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Qudrat Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahsili_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Tahsili Score'),
        ),
        migrations.AddField(
            model_name='tarifireceptiondate',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifi_reception_dates', to='undergraduate_admission.AdmissionSemester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='user',
            name='tarifi_week_attendance_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='undergraduate_admission.TarifiReceptionDate', verbose_name='Tarifi Week Attendance Date'),
        ),
    ]
