# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-14 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0034_user_eligible_for_housing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tarifi_week_attendance_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tarifi Week Attendance Date'),
        ),
    ]
