# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-27 11:34
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import undergraduate_admission.media_handlers
import undergraduate_admission.validators


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0035_user_tarifi_week_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantDateSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Arabic Title')),
                ('title_en', models.CharField(max_length=200, verbose_name='English Title')),
                ('description_ar', models.CharField(max_length=300, null=True, verbose_name='Arabic Description')),
                ('description_en', models.CharField(max_length=300, null=True, verbose_name='English Description')),
                ('show', models.BooleanField(default=True, verbose_name='Show')),
                ('display_order', models.PositiveSmallIntegerField(null=True, verbose_name='Display Order')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CutOff',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('undergraduate_admission.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driving License'),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_driving_license, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Driving_License File'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_full_name_ar',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Student Faull Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_full_name_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Student Faull Name (English)'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Registration'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_registration_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_vehicle_registration, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Vehicle Registration File'),
        ),
    ]
