# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import undergraduate_admission.media_handlers
import undergraduate_admission.validators


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0036_cutoff_importantdatesidebar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantdatesidebar',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driving License'),
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_driving_license, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Driving_License File'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_full_name_ar',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Student Faull Name (Arabic)'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_full_name_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Student Faull Name (English)'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Registration'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_registration_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_vehicle_registration, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Vehicle Registration File'),
        ),
    ]
