# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0036_auto_20170511_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phase3_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 3 End Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='phase3_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 3 Start Date'),
        ),
    ]
