# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0036_auto_20170427_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsemester',
            name='phase3_end_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 3 End Date'),
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='phase3_start_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 3 Start Date'),
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='phase4_end_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 4 End Date'),
        ),
        migrations.AddField(
            model_name='admissionsemester',
            name='phase4_start_date',
            field=models.DateTimeField(null=True, verbose_name='Phase 4 Start Date'),
        ),
    ]
