# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0037_auto_20170514_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phase3_submit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phase 3 Submit Date'),
        ),
    ]
