# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-30 11:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0037_auto_20170427_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionsemester',
            options={'verbose_name': 'Admission Semester', 'verbose_name_plural': 'Admission Semester'},
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name_plural': 'Agreements'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-display_order'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='deniedstudent',
            options={'verbose_name_plural': 'Denied Students'},
        ),
        migrations.AlterModelOptions(
            name='distinguishedstudent',
            options={'verbose_name_plural': 'Distinguished Students'},
        ),
        migrations.AlterModelOptions(
            name='graduationyear',
            options={'ordering': ['-display_order'], 'verbose_name_plural': 'Graduation Years'},
        ),
        migrations.AlterModelOptions(
            name='importantdatesidebar',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Important Date Sidebar'},
        ),
        migrations.AlterModelOptions(
            name='kfupmidspool',
            options={'verbose_name_plural': 'KFUPM ID Pools'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['display_order', 'nationality_en'], 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AlterModelOptions(
            name='registrationstatus',
            options={'verbose_name_plural': 'Registration Status'},
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_gpa_yesser',
            field=models.FloatField(blank=True, null=True, verbose_name='High School GPA - Yesser'),
        ),
        migrations.AddField(
            model_name='user',
            name='qudrat_score_yesser',
            field=models.FloatField(blank=True, null=True, verbose_name='Qudrat Score - Yesser'),
        ),
        migrations.AddField(
            model_name='user',
            name='tahsili_score_yesser',
            field=models.FloatField(blank=True, null=True, verbose_name='Tahsili Score - Yesser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, help_text='Mobile number should be of this format "9665xxxxxxxx". Use English numerals only. Please make sure to activate promotional messages from your mobile provider.', max_length=12, null=True, validators=[django.core.validators.RegexValidator('^(9665|٩٦٦٥)\\d{8}$', message='You have entered an invalid mobile number')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_full_name_ar',
            field=models.CharField(blank=True, help_text='Your Arabic full name should be similar to Identification ID/Iqama.', max_length=400, null=True, verbose_name='Student Full Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_full_name_en',
            field=models.CharField(blank=True, help_text='Your English full name should be similar to Passport or high school certificate.', max_length=400, null=True, verbose_name='Student Full Name (English)'),
        ),
    ]
