# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0038_user_phase3_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=128, null=True),
        ),
    ]
