# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-01 11:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import undergraduate_admission.media_handlers
import undergraduate_admission.validators


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0038_auto_20170430_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vehicle_registration',
        ),
        migrations.AddField(
            model_name='user',
            name='have_a_vehicle',
            field=models.BooleanField(default=False, help_text='This will let us help you better to get you a permit to enter campus.', verbose_name='Do you have a vehicle you want to register?'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_plate_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle Plate No.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_license_file',
            field=models.FileField(blank=True, null=True, upload_to=undergraduate_admission.media_handlers.upload_location_driving_license, validators=[undergraduate_admission.validators.validate_file_extension], verbose_name='Driving License File'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_gpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='High School GPA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='high_school_gpa_yesser',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='High School GPA - Yesser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qudrat_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Qudrat Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qudrat_score_yesser',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Qudrat Score - Yesser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahsili_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tahsili Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tahsili_score_yesser',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tahsili Score - Yesser'),
        ),
    ]
