# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-18 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0039_auto_20170516_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saudi_mother_gov_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Saudi Mother Government ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=128),
        ),
    ]
