# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 14:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0040_auto_20170502_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifiReceptionDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_date', models.CharField(max_length=600, null=True, verbose_name='Reception Date')),
                ('slots', models.PositiveSmallIntegerField(default=300, null=True, verbose_name='Slots')),
                ('slot_start_date', models.DateTimeField(null=True, verbose_name='Start Date')),
                ('slot_end_date', models.DateTimeField(null=True, verbose_name='End Date')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifi_reception_dates', to='undergraduate_admission.AdmissionSemester', verbose_name='Semester')),
            ],
            options={
                'verbose_name_plural': 'Tarifi Reception Dates',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='admission_letter_note',
        ),
        migrations.AddField(
            model_name='user',
            name='english_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='English Level'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_placement_test_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='English Placement Test Score'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_speaking_test_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='English Speaking Test Score'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tarifi_week_attendance_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='undergraduate_admission.TarifiReceptionDate', verbose_name='Tarifi Week Attendance Date'),
        ),
    ]
