# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0040_auto_20170518_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roommate_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Roommate ID'),
        ),
    ]
