# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0041_auto_20170502_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionsemester',
            options={'verbose_name': 'Admission Semester', 'verbose_name_plural': 'Admission: Admission Semesters'},
        ),
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name_plural': 'Admission and Student Affairs: Agreements'},
        ),
        migrations.AlterModelOptions(
            name='agreementitem',
            options={'ordering': ['agreement', '-display_order'], 'verbose_name_plural': 'Admission and Student Affairs: Agreement Items'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-display_order'], 'verbose_name_plural': 'Admission: Cities'},
        ),
        migrations.AlterModelOptions(
            name='deniedstudent',
            options={'verbose_name_plural': 'Admission: Denied Students'},
        ),
        migrations.AlterModelOptions(
            name='distinguishedstudent',
            options={'verbose_name_plural': 'Admission: Distinguished Students'},
        ),
        migrations.AlterModelOptions(
            name='graduationyear',
            options={'ordering': ['-display_order'], 'verbose_name_plural': 'Admission: Graduation Years'},
        ),
        migrations.AlterModelOptions(
            name='importantdatesidebar',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Admission: Important Date Sidebar'},
        ),
        migrations.AlterModelOptions(
            name='kfupmidspool',
            options={'verbose_name_plural': 'Registrar: KFUPM ID Pools'},
        ),
        migrations.AlterModelOptions(
            name='lookup',
            options={'ordering': ['lookup_type', '-display_order'], 'verbose_name_plural': 'Admission: Look ups'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['display_order', 'nationality_en'], 'verbose_name_plural': 'Admission: Nationalities'},
        ),
        migrations.AlterModelOptions(
            name='registrationstatus',
            options={'verbose_name_plural': 'Admission: Registration Status'},
        ),
        migrations.AlterModelOptions(
            name='registrationstatusmessage',
            options={'verbose_name_plural': 'Admission: Registration Status Messages'},
        ),
        migrations.AlterModelOptions(
            name='tarifireceptiondate',
            options={'verbose_name_plural': 'Admission: Tarifi Reception Dates'},
        ),
    ]
