# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-31 10:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0041_user_roommate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='high_school_gpa_yesser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qudrat_score_yesser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tahsili_score_yesser',
        ),
        migrations.AddField(
            model_name='user',
            name='high_school_gpa_student_entry',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='High School GPA'),
        ),
        migrations.AddField(
            model_name='user',
            name='qudrat_score_student_entry',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Qudrat Score - Entered by Student'),
        ),
        migrations.AddField(
            model_name='user',
            name='tahsili_score_student_entry',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Tahsili Score - Entered by Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saudi_mother_gov_id',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{9,11}$', message='You have entered an invalid Government ID')], verbose_name='Saudi Mother Government ID'),
        ),
    ]
