# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undergraduate_admission', '0042_auto_20170509_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CutOff',
        ),
    ]
