# Generated by Django 2.1.5 on 2019-04-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('undergraduate_admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='housing_user', serialize=False, to='undergraduate_admission.AdmissionRequest')),
                ('facebook', models.URLField(blank=True, max_length=150, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, max_length=150, null=True, verbose_name='Twitter')),
                ('sleeping', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sleeping')),
                ('light', models.CharField(blank=True, max_length=150, null=True, verbose_name='Light')),
                ('room_temperature', models.CharField(blank=True, max_length=150, null=True, verbose_name='Room Temperature')),
                ('visits', models.CharField(blank=True, max_length=150, null=True, verbose_name='Visits')),
                ('interests_and_hobbies', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Interests And Hobbies')),
                ('searchable', models.NullBooleanField(verbose_name='Searchable')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=20, null=True, verbose_name='Building')),
                ('room', models.CharField(max_length=20, null=True, verbose_name='Room')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
            ],
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('W1', 'Requesting Student Withdrawn'), ('W2', 'Requested Student Withdrawn'), ('E', 'Expired'), ('C', 'Cancelled By Requester')], default='P', max_length=10, null=True, verbose_name='Status')),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Request Date')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On')),
                ('assigned_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residing', to='find_roommate.Room', verbose_name='Assigned Room')),
                ('requested_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_request_received', to='undergraduate_admission.AdmissionRequest')),
                ('requesting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_request_sent', to='undergraduate_admission.AdmissionRequest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'room')},
        ),
    ]
