# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_roommate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinguser',
            name='facebook',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='housinguser',
            name='twitter',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Twitter'),
        ),
    ]
