# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-01 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_roommate', '0002_room_roommaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommaterequest',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('W1', 'Requester Withdrawn'), ('R', 'Rejected'), ('A', 'Accepted'), ('W2', 'Requested Withdrawn'), ('E', 'Expired')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
