# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-11 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_roommate', '0003_auto_20160807_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housinguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='housing_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
