# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_roommate', '0003_auto_20170801_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommaterequest',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('W1', 'Requesting Student Withdrawn'), ('W2', 'Requested Student Withdrawn'), ('E', 'Expired')], default='P', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('building', 'room')]),
        ),
    ]
