# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-03 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_roommate', '0004_auto_20170803_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommaterequest',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residing', to='find_roommate.Room', verbose_name='Assigned Room'),
        ),
    ]
