# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-04 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_roommate', '0006_auto_20170814_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommaterequest',
            name='requesting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_request_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
