- name: Deploy Qabool
  hosts: application-servers
  become: yes
  become_user: root

  # common variables to all environments
  # for environment-specific variables, see:
  # environments/<env-name>/group_vars/all/vars.yml
  vars:
    django_project_name: qabool
    vault_url: https://vault.itc.kfupm.edu.sa
    django_project_admin_username: almaaesh
    django_project_admin_email: almaaesh@kfupm.edu.sa
    django_project_package_name: qabool
    buildbot_autobuild: false
    ssl_cert_path: "/etc/ssl/certs"

    apache_authn: cas
    apache_auth:
      - path: /ar/admin/
        authn_type: cas
        authz_type: none
      - path: /en/admin/
        authn_type: cas
        authz_type: none
      - path: /ar/manage/
        authn_type: cas
        authz_type: none
      - path: /en/manage/
        authn_type: cas
        authz_type: none
      - path: /admin_files/
        authn_type: cas
        authz_type: none

    apache_extra_modules:
      - xsendfile
    apache_extra_config: |
      XSendFile On
      XSendFilePath {{ django_project_media_dir }}

    admins:
      - name: Abdullah Joud
        email: joud@kfupm.edu.sa

    uwsgi_processes: 64

  vars_prompt:
    - name: ad_username
      prompt: Your Active Directory username
      private: no

    - name: ad_password
      prompt: Your Active Directory password
      private: yes


  # tasks to be performed before role tasks, if any
  pre_tasks:

    - pause:
        prompt: Your Active Directory username
      when: not buildbot_autobuild
      register: ad_username
      connection: local

    - pause:
        prompt: Your Active Directory password
        echo: no
      when: not buildbot_autobuild
      register: ad_password
      connection: local

    - name: Vault authentication
      uri:
        url: "{{ vault_url }}/v1/auth/ldap/login/{{ ad_username.user_input }}"
        method: POST
        body: {"password": "{{ ad_password.user_input }}"}
        body_format: json
      connection: local
      become: no
      register: auth
      when: not buildbot_autobuild

    - name: set token
      set_fact:
        vault_access_token: "{{ auth.json.auth.client_token }}"
      when: not buildbot_autobuild

    - name: Retrieve secret key from Vault
      set_fact:
        secret_key: "{{ lookup('hashi_vault', 'secret=secret/{{ env }}/operations/apps/qabool/secret_key:value token={{ vault_access_token }} url={{ vault_url }} cacert={{ ssl_cert_path }}') }}"
      connection: local

    - name: Retrieve database password from vault
      set_fact:
        database_password: "{{ lookup('hashi_vault', 'secret=secret/{{ env }}/database/apps/qabool/database_password:value token={{ vault_access_token }} url={{ vault_url }} cacert={{ ssl_cert_path }}') }}"
      connection: local

    - name: Retrieve email password from vault
      set_fact:
        email_password: "{{ lookup('hashi_vault', 'secret=secret/{{ env }}/email/apps/qabool/email_password:value token={{ vault_access_token }} url={{ vault_url }} cacert={{ ssl_cert_path }}') }}"
      connection: local

    - name: Retrieve sms gateway app sid from Vault
      set_fact:
        sms_gateway_app_sid: "{{ lookup('hashi_vault', 'secret=secret/{{ env }}/email/apps/qabool/sms_gateway_app_sid:value token={{ vault_access_token }} url={{ vault_url }} cacert={{ ssl_cert_path }}') }}"
      connection: local

    - name: Generate local settings
      set_fact:
        django_project_local_settings: "{{ lookup('template', 'local_settings.py.j2') }}"

    - name: Install mod_xsendfile for apache
      apt: pkg=libapache2-mod-xsendfile state=installed

    - name: Install required software packages for zeep - python3-lxml build-deps
      apt: pkg=python3-lxml state=build-dep

    - name: Install required software packages for zeep - additional optional build dependencies
      apt: pkg="{{ item }}" state=installed
      with_items:
        - libxml2-dev
        - libxslt-dev
        - python-defusedxml

  roles:
    - django-project

  # tasks to be performed after role tasks, if any
  post_tasks:
    - name: mount nfs media files repository from filer
      mount:
        name: "{{ django_project_media_dir }}"
        src: "{{ qabool_media_files_remote_path }}"
        fstype: nfs
        state: mounted
