- name: Deploy Qabool
  hosts: application-servers
  become: yes
  become_user: root

  # common variables to all environments
  # for environment-specific variables, see:
  # environments/<env-name>/group_vars/all/vars.yml
  vars:
    django_project_name: qabool
    django_project_admin_username: joud
    django_project_admin_email: joud@kfupm.edu.sa
    django_project_package_name: qabool
    apache_authn: cas
    apache_authn_urls:
      - /ar/admin/
      - /en/admin/
      - /ar/manage/
      - /en/manage/
#    apache_extra_modules: 
#      - mod_xsendfile
#    apache_extra_config: |
#      XSendFile True

    admins:
      - name: Abdullah Joud
        email: joud@kfupm.edu.sa
    uwsgi_processes: 2

  vars_prompt:
    - name: ad_username
      prompt: Your Active Directory username
      private: no

    - name: ad_password
      prompt: Your Active Directory password
      private: yes


  # tasks to be performed before role tasks, if any
  pre_tasks:
    - name: Vault authentication
      uri:
        url: https://vault-1.test.kfupm.edu.sa:8200/v1/auth/ldap/login/{{ ad_username }}
        method: POST
        body: {"password": "{{ ad_password }}"}
        body_format: json
        validate_certs: no
      connection: local
      become: no
      register: auth

    - name: Retrieve secret key from Vault
      uri:
        url: https://vault-1.test.kfupm.edu.sa:8200/v1/secret/{{ env }}/apps/qabool/secret_key
        HEADER_X-Vault-Token: "{{ auth.json.auth.client_token }}"
        validate_certs: no
      connection: local
      become: no
      register: secret_key

    - name: Retrieve database password from Vault
      uri:
        url: https://vault-1.test.kfupm.edu.sa:8200/v1/secret/{{ env }}/apps/qabool/database_password
        HEADER_X-Vault-Token: "{{ auth.json.auth.client_token }}"
        validate_certs: no
      connection: local
      become: no
      register: database_password

    - name: Retrieve email password from Vault
      uri:
        url: https://vault-1.test.kfupm.edu.sa:8200/v1/secret/{{ env }}/apps/qabool/email_password
        HEADER_X-Vault-Token: "{{ auth.json.auth.client_token }}"
        validate_certs: no
      connection: local
      become: no
      register: email_password
      
    - name: Retrieve sms gateway app sid from Vault
      uri:
        url: https://vault-1.test.kfupm.edu.sa:8200/v1/secret/{{ env }}/apps/qabool/sms_gateway_app_sid
        HEADER_X-Vault-Token: "{{ auth.json.auth.client_token }}"
        validate_certs: no
      connection: local
      become: no
      register: sms_gateway_app_sid

    - name: Generate local settings
      set_fact:
        django_project_local_settings: "{{ lookup('template', 'local_settings.py.j2') }}"
        
#    - name: Install mod_xsendfile for apache
#      apt: pkg=libapache2-mod-xsendfile state=installed
        

  roles:
    - django-project

  # tasks to be performed after role tasks, if any
  post_tasks:
    - name: mount nfs media files repository from filer
      mount:
        name: "{{ django_project_media_dir }}"
        src: "{{ qabool_media_files_remote_path }}"
        fstype: nfs
        state: mounted
