- name: Deploy Qabool
  hosts: qabool.kfupm.edu.sa
  tasks:
    - name: Install required software packages
      apt: pkg="{{ item }}" state=installed
      with_items:
        - build-essential
        - libpq-dev
        - python3
        - python3-dev
        - python3-virtualenv
        - virtualenvwrapper

    - name: Create appilcation user
      user: name=qabool system=yes

    - name: Get the application code
      hg:
        repo: http://hg.itc.kfupm.edu.sa/apps/qabool
        dest: /opt/qabool
        force: yes
        revision: stable

    - name: Create virtualenv
      pip:
        virtualenv: /opt/qabool_venv
        virtualenv_python: python3
        requirements: /opt/qabool/qabool/requirements.txt

    - name: Configure application
      template:
        src: local_settings.py.j2
        dest: /opt/qabool/qabool/qabool/local_settings.py
        owner: root
        group: qabool
        mode: 0640
