- name: Deploy Qabool
  hosts: qabool
  become: yes
  become_user: root

  vars:
    install_dir: /opt/qabool
    venv_dir: /opt/qabool_venv

  tasks:
    - name: Install required software packages
      apt: pkg="{{ item }}" state=installed
      with_items:
        - build-essential
        - libpq-dev
        - python3
        - python3-dev
        - python3-virtualenv
        - virtualenvwrapper
        - gettext
        - nginx-full

    - name: Create appilcation user
      user: name=qabool system=yes

    - name: Get the application code
      hg:
        repo: http://hg.itc.kfupm.edu.sa/apps/qabool
        dest: "{{ install_dir }}"
        #revision: stable

    - name: Set file permissions
      file:
        path: "{{ install_dir }}"
        owner: root
        group: qabool
        mode: 0640

    - name: Create virtualenv
      pip:
        virtualenv: "{{ venv_dir }}"
        virtualenv_python: python3
        requirements: "{{ install_dir }}/qabool/requirements.txt"

    - name: Configure application
      template:
        src: local_settings.py.j2
        dest: "{{ install_dir }}/qabool/qabool/local_settings.py"
        owner: root
        group: qabool
        mode: 0640

    - name: Migrate database
      command: "{{ venv_dir }}/bin/python manage.py migrate"
      args:
        chdir: "{{ install_dir }}/qabool"

    - name: Compile translation messages
      command: "{{ venv_dir }}/bin/python manage.py compilemessages --locale ar"
      args:
        chdir: "{{ install_dir }}/qabool"

    - name: Load initial data (fixtures)
      command: "{{ venv_dir }}/bin/python manage.py loaddata initial-data.json"
      args:
        chdir: "{{ install_dir }}/qabool"
