= Detailed New System Analysis Document for Project Name
FIRST-NAME LAST-NAME <EMAIL>; SECOND-AUTHOR; ...
VERSION, DATE, VERSION DESCIPTION

.Proprietary Information

This document is the property of Information Technology Center (ITC),
King Fahd University of Petroleum and Minerals, Kingdom of Saudi
Arabia, and is assigned the classification rating of Internal.

The contents of this document are proprietary information and may not
be distributed or disclosed, published or copied without the ITC's
written permission.

== Product Scope

< Overview the project briefly. Tell the name of the product to be created. Explain what it will do in general terms. If needed, tell what it will not do. Describe the need, context, and rationale for the system. Discuss how it fits into the overall business or strategic objectives of the organization. Describe previous versions of the software (if any) and the relationship with the proposed version. If a separate vision and scope document is available, refer to it rather than duplicating its contents here. The explicit functionality of the project is described in the sections below.>


== Product Functions

<Summarize the major functions the product must perform or must let the user perform. Only a high level summary (such as a bullet list) is needed here. Organize the functions to make them understandable to any reader of the document. A picture of the major groups of related requirements and how they relate, such as a top level data flow diagram or object class diagram, is often effective.>


== As - Is Process

<BPMN 2.0 or any other explanatory workflow diagrams can be used here to describe the overall functions of the product.>


== To - Be Process

<BPMN 2.0 or any other explanatory workflow diagrams can be used here to describe the overall functions of the product.> +
<Detailed Use Cases should be explained.>



== Detailed Functional Requiremenst
<This template illustrates organizing the functional requirements for the product by system features (functional requirement by functional requirement), the major services provided by the product. You may prefer to organize this section by *_use case_*, mode of operation, *_user class_*, object class, functional hierarchy, or combinations of these, whatever makes the most logical sense for your product.> +

*Functional Requirement 1* +

<Don’t really say “Functional Requirement 1.” State the feature name in just a few words.
List each functionality of the system in full detail using full use case descriptions. See Use Case Description document. The organization of this chapter should facilitate the correct design of the system and support validation testing. Each use case must include validity checks on inputs, the sequence of operations, and responses to abnormal situations.
State Transition Diagrams may be used effectively to describe complicated sequences of operations. It is essential that this section be as clear as possible.

_ID: FR1_ +

. _Description and Priority:_
Provide a short description of the feature and indicate whether it is of High, Medium, or Low priority. You could also include specific priority component ratings, such as benefit, penalty, cost, and risk (each rated on a relative scale from a low of 1 to a high of 9).

. _Stimulus/Response Sequences:_ <List the sequences of user actions and system responses that stimulate the behavior defined for this feature. These will correspond to the dialog elements associated with use cases.>
<Full use case descriptions can be used here>
. _Functional Requirements:_<Itemize the detailed functional requirements associated with this feature. These are the software capabilities that must be present in order for the user to carry out the services provided by the feature, or to execute the use case. Include how the product should respond to anticipated error conditions or invalid inputs. Requirements should be concise, complete, unambiguous, verifiable, and necessary. Use “TBD” as a placeholder to indicate when necessary information is not yet available.>

<Each requirement should be uniquely identified with a sequence number or a meaningful tag of some kind.>

- REQ-1:
- REQ-2:


== Other Nonfunctional Requirements
<State any nonfunctional requirements here>

- *Performance Requirements* +
<If there are performance requirements for the product under various circumstances, state them here and explain their rationale, to help the developers understand the intent and make suitable design choices. Specify the timing relationships for real time systems. Make such requirements as specific as possible. You may need to state performance requirements for individual functional requirements or features.> +
- *Safety Requirements* +
<Specify those requirements that are concerned with possible loss, damage, or harm that could result from the use of the product. Define any safeguards or actions that must be taken, as well as actions that must be prevented. Refer to any external policies or regulations that state safety issues that affect the product’s design or use. Define any safety certifications that must be satisfied.>
- *Security Requirements* +
<Specify any requirements regarding security or privacy issues surrounding use of the product or protection of the data used or created by the product. Define any user identity authentication requirements. Refer to any external policies or regulations containing security issues that affect the product. Define any security or privacy certifications that must be satisfied.>

- *Software Quality Attributes* +
<Specify any additional quality characteristics for the product that will be important to either the customers or the developers. Some to consider are: adaptability, availability, correctness, flexibility, interoperability, maintainability, portability, reliability, reusability, robustness, testability, and usability. Write these to be specific, quantitative, and verifiable when possible. At the least, clarify the relative preferences for various attributes, such as ease of use over ease of learning.>
- *Business Rules*
<List any operating principles about the product, such as which individuals or roles can perform which functions under specific circumstances. These are not functional requirements in themselves, but they may imply certain functional requirements to enforce the rules.>
