= Software Requirements Specification for PROJECT-NAME
FIRST-NAME LAST-NAME <EMAIL>; SECOND-AUTHOR; ...
VERSION, DATE, VERSION DESCIPTION

include::includes/proprietary-information.adoc[]

== Introduction

=== Purpose and Intended Audience

< Clearly state the purpose of this document and its intended
audiences. Note that this subsection does not describe the project. >

=== Product Scope

< Brief overview of the project. Tell the name of the product to be
created. Explain what it will do in general terms. If needed, tell
what it will not do. Describe the need, context, and rationale for the
system. Discuss how it fits into the overall business or strategic
objectives of the organization. Describe previous versions of the
software (if any) and the relationship with the proposed version . If
a separate vision and scope document is available, refer to it rather
than duplicating its contents here. The explicit functionality of the
project is described in the sections below. >

=== Definitions, Acronyms, and Abbreviations

[horizontal]
KFUPM::	King Fahd University of Petroleum & Minerals
ITC::	Information technology center
ADIS::	Administrative information system
BI:: Business intelligence
SMS:: Short message service


=== References

None.

=== Overview of Document

The document is organized as follows. Section 2 gives an overall
description of the system, including the characteristics of its users
and its main functionality. The external interface requirements will be discussed in Section 3.
The functional requirements of the system will discussed in detail in Section 4.
Section 5 explains the other nonfunctional requirements of the system.


== Overall Description
NOTE: TODO: Joud

=== Product Perspective

_Admission_ system allows the students to apply at KFUPM through a web browser
and support multilingual. The students can access the system during registration period only.
It also, cover application administrators for data manipulation.

=== Product Functions

Student functions

* Student: Student registration with Initial agreements
* Student: Calculate student GPA
* Student: Student login
* Student: Student dashboard
* Student: Student results
* Student: Confirmation (only for accepted student by admission office)
* Student: Student withdrawal and the agreements(after confirmation the student
  can withdrawal anytime)
* Student: Assign KFUPM ID to students who confirmed
* Student: Complete student information
* Student: Upload required documents
* Student: Re-upload the documents (if missing something)
* Student: Print admission letter
* Student: Print medical report
* Student: Print two letters belong to student housing
* Log out

Application administrator functions

NOTE: TODO: Joud plz list all BI reports and administrator dashboard here

* Login
* BI: System Statistics Report
* BI:
* Log out

<Summarize the major functions the product must perform or must let
the user perform. Details will be provided in Section 3, so only a
high level summary (such as a bullet list) is needed here. Organize
the functions to make them understandable to any reader of the SRS. A
picture of the major groups of related requirements and how they
relate, such as a top level data flow diagram or object class diagram,
is often effective.>

<BPMN 2.0 or any other explanatory workflow diagrams can be used here
to describe the overall functions of the product.>

=== User Classes and Characteristics
NOTE: TODO: Bassam

<Identify the various user classes that you anticipate will use this
product. User classes may be differentiated based on frequency of use,
subset of product functions used, technical expertise, security or
privilege levels, educational level, or experience. Describe the
pertinent characteristics of each user class. Certain requirements may
pertain only to certain user classes. Distinguish the most important
user classes for this product from those who are less important to
satisfy.>

< Describe the characteristics of the intended users in terms of
experience and technical expertise. At a minimum, give the
characteristics of the interface for each class of users, that is,
screen formats, page/window layouts, content of reports or menus. How
should the system appear to the user? How detailed should error
messages be? If you are using prototyping, sample interfaces may be
provided but make clear what principles are required to allow
consistent modifications. Sample user interfaces may be placed in an
Appendix to this volume. >

=== Operating Environment

None.

=== Design and Implementation Constraints
None.
<Describe any items or issues that will limit the options available to
the developers. These might include: corporate or regulatory policies;
hardware limitations (timing requirements, memory requirements);
interfaces to other applications; specific technologies, tools, and
databases to be used; parallel operations; language requirements;
communications protocols; security considerations; design conventions
or programming standards (for example, if the customer’s organization
will be responsible for maintaining the delivered software).>

<Remember that this section is for the user (stakeholders). A full set
of non-functional requirements for the developer is contained in
section 5.>

=== User Documentation

None.

=== Assumptions and Dependencies
NOTE: TODO: Joud put some information about the yesser?!


<List any assumed factors (as opposed to known facts) that could
affect the requirements stated in the SRS. These could include
third-party or commercial components that you plan to use, issues
around the development or operating environment, or constraints. The
project could be affected if these assumptions are incorrect, are not
shared, or change. Also identify any dependencies the project has on
external factors, such as software components that you intend to reuse
from another project, unless they are already documented elsewhere
(for example, in the vision and scope document or the project plan).>


== External Interface Requirements

=== User Interfaces

NOTE: TODO: Joud

<Describe the logical characteristics of each interface between the
software product and the users. This may include sample screen images,
any GUI standards or product family style guides that are to be
followed, screen layout constraints, standard buttons and functions
(e.g., help) that will appear on every screen, keyboard shortcuts,
error message display standards, and so on. Define the software
components for which a user interface is needed. Details of the user
interface design should be documented in a separate user interface
specification.>

<High-level wireframes for all user interfaces should be presented
here.>

=== Hardware Interfaces

None

=== Software Interfaces
NOTE: TODO: Joud

<Describe the connections between this product and other specific
software components (name and version), including databases, operating
systems, tools, libraries, and integrated commercial
components. Identify the data items or messages coming into the system
and going out and describe the purpose of each. Describe the services
needed and the nature of communications. Refer to documents that
describe detailed application programming interface
protocols. Identify data that will be shared across software
components. If the data sharing mechanism must be implemented in a
specific way (for example, use of a global data area in a multitasking
operating system), specify this as an implementation constraint.>

=== Communications Interfaces

- The system must support email and SMS notifications for different activities.
These notifications include:
** Notifying students when the registration has been submitted successfully to admission.
** Notifying students when they confirm and accept study at KFUPM.
** Notifying both application administrator and
students when the withdrawal has been submitted to admission.

== Functional Requirements
NOTE: TODO: Joud

<This template illustrates organizing the functional requirements for
the product by system features (functional requirement by functional
requirement), the major services provided by the product. You may
prefer to organize this section by use case, mode of operation, user
class, object class, functional hierarchy, or combinations of these,
whatever makes the most logical sense for your product.>

=== Functional Requirement 1

<Don’t really say “Functional Requirement 1.” State the feature name
in just a few words. List each functionality of the system in full
detail using full use case descriptions. See Use Case Description
document. The organization of this chapter should facilitate the
correct design of the system and support validation testing. Each use
case must include validity checks on inputs, the sequence of
operations, and responses to abnormal situations.

State Transition Diagrams may be used effectively to describe
complicated sequences of operations. It is essential that this section
be as clear as possible.

Each item here is explicitly cross-referenced back to section
3.1. Each item here must be uniquely identified to allow backward
references from the design and testing documents. When those documents
are finished, forward references to their specific sections are added
here. >

ID: FR1

==== Description and Priority
NOTE: TODO: Joud and Bassam

<Provide a short description of the feature and indicate whether it is
of High, Medium, or Low priority. You could also include specific
priority component ratings, such as benefit, penalty, cost, and risk
(each rated on a relative scale from a low of 1 to a high of 9).>

==== Stimulus/Response Sequences
NOTE: TODO: Joud and Bassam

<List the sequences of user actions and system responses that
stimulate the behavior defined for this feature. These will correspond
to the dialog elements associated with use cases.>

<Full use case descriptions can be used here>

==== Functional Requirements

<Itemize the detailed functional requirements associated with this
feature. These are the software capabilities that must be present in
order for the user to carry out the services provided by the feature,
or to execute the use case. Include how the product should respond to
anticipated error conditions or invalid inputs. Requirements should be
concise, complete, unambiguous, verifiable, and necessary. Use “TBD”
as a placeholder to indicate when necessary information is not yet
available.>

<Each requirement should be uniquely identified with a sequence number
or a meaningful tag of some kind.>

REQ-1 :: <details>
REQ-2 :: <details>

=== Functional Requirement 2 (and so on)


== Other Nonfunctional Requirements

=== Performance Requirements
** The website should host on cloud server that can provide adequate response time.
** The software must support 50,000+ requesters which will on a busy day generate
20,000 interaction.
** The system response time must be less than 10 seconds for the user interface.

<If there are performance requirements for the product under various
circumstances, state them here and explain their rationale, to help
the developers understand the intent and make suitable design
choices. Specify the timing relationships for real time systems. Make
such requirements as specific as possible. You may need to state
performance requirements for individual functional requirements or
features.>

=== Safety Requirements
None.
<Specify those requirements that are concerned with possible loss,
damage, or harm that could result from the use of the product. Define
any safeguards or actions that must be taken, as well as actions that
must be prevented. Refer to any external policies or regulations that
state safety issues that affect the product’s design or use. Define
any safety certifications that must be satisfied.>

=== Security Requirements
None.
<Specify any requirements regarding security or privacy issues
surrounding use of the product or protection of the data used or
created by the product. Define any user identity authentication
requirements. Refer to any external policies or regulations containing
security issues that affect the product. Define any security or
privacy certifications that must be satisfied.>

=== Software Quality Attributes

None.
<Specify any additional quality characteristics for the product that
will be important to either the customers or the developers. Some to
consider are: adaptability, availability, correctness, flexibility,
interoperability, maintainability, portability, reliability,
reusability, robustness, testability, and usability. Write these to be
specific, quantitative, and verifiable when possible. At the least,
clarify the relative preferences for various attributes, such as ease
of use over ease of learning.>

===  Business Rules

[horizontal]
Developers and designers:: could change the design layout of the website and modify the code.
Students:: they can register, login to the system, submit the forms, confirm, upload required documents and
print documents.
Moderators:: they are supporting students who forget the password, changing
student email and verify uploaded student documents.
Application Administrator:: ......

<List any operating principles about the product, such as which
individuals or roles can perform which functions under specific
circumstances. These are not functional requirements in themselves,
but they may imply certain functional requirements to enforce the
rules.>

== Other Requirements

*	The system data must be backed up every day and the backup copies stored in
 another server at different location for disaster recovery.
*	The system should provide data security that will prevent direct and
 unauthorized access (add, update, delete, query).

<Define any other requirements not covered elsewhere in the SRS. This
might include database requirements, internationalization
requirements, legal requirements, reuse objectives for the project,
and so on. Add any new sections that are pertinent to the project.>

[appendix]
== Analysis Models

<Optionally, include any pertinent analysis models, such as data flow
diagrams, class diagrams, state-transition diagrams, or
entity-relationship diagrams.>

[appendix]
== To Be Determined List

<Collect a numbered list of the TBD (to be determined) references that
remain in the SRS so they can be tracked to closure.>

Source: http://www.frontiernet.net/~kwiegers/process_assets/srs_template.doc
